[package]
name = "cortex-m-aircr-prigroup"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.6.13"
cortex-m-semihosting = "0.3.7"
panic-semihosting = "0.5.6"
stm32h7 = {version = "0.13.0", features = ["stm32h743v", "rt"]}
